### PR TITLE
3.0.0 - Closes #13

### LINKED ISSUE #13: Dependency error after NodeJS update.
Hey guys, anyone know when html-injector will update dependencies? I start to get this error since i update node.

I really appreciate any kind of help on that issue:

npm install bs-html-injector --save-dev

> contextify@0.1.14 install /Users/Projects/app/node_modules/contextify
> node-gyp rebuild

14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Projects/app/node_modules/contextify
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

Thanks!

### PR DESCRIPTION
**Pull request by polarathene**
Dependencies updated for Node 4.2.0 (LTS) compatibility.

### CODE REVIEW

**Comment by polarathene** [comment]
@shakyShane rebased with force-push, seems like I renamed the commit messages correctly.

**Comment by shakyShane** [comment]
Perfect, thanks!

**Comment by shakyShane** [comment]
on npm now

bs-html-injector@3.0.0

**Comment by polarathene** [comment]
Awesome thanks :)

**Pull request merged**
